###listar cursos publicados
GET http://localhost:4300/api/v1/courses/published/all

###obtener curso por slug
GET http://localhost:4300/api/v1/courses/slug/introduction-to-kubernetes

### Crear curso
POST http://localhost:4300/api/v1/courses/

Content-Type: application/json

{
    "title": "Introduction to Kubernetes",
    "description": "Learn the basics of Kubernetes, the leading container orchestration platform.",
    "short_description": "Basics of Kubernetes",
    "price": 199.99,
    "thumbnail_url": "http://example.com/kubernetes-thumbnail.jpg",
    "preview_video_url": "http://example.com/kubernetes-preview.mp4",
    "course_type": "free",
    "duration_hours": 40,
    "level": "Beginner",
    "published": true,

}