### Verificar si el usuario esta autenticado
GET http://localhost:4300/api/v1/auth/verify-token

### Registrar usuario
POST http://localhost:4300/api/v1/auth/register
Content-Type: application/json

{
    "name_user": "Jose Santana",
    "email_user": "jose.santana@example.com",
    "password_hash": "securePassword123",
    "username": "josesantana",
    "rol_user": "student"
}

### Login usuario
POST http://localhost:4300/api/v1/auth/login
Content-Type: application/json

{
    "email_user": "jose.santana@example.com",
    "password_hash": "securePassword123"
}

### Cerrar sesión
POST http://localhost:4300/api/v1/auth/logout

### Obtener información del usuario
GET http://localhost:4300/api/v1/auth/me


