### Verificar si el usuario esta autenticado
GET http://localhost:4300/api/v1/auth/verify-token

### Registrar usuario
POST http://localhost:4300/api/v1/users/register
Content-Type: application/json

{
    "name_user": "Jose S. Santana",
    "email_user": "profesor@example.com",
    "password_user": "securePassword123",
    "username": "ProfesorJSantana",
    "role_user": "instructor"
}

### Login usuario
POST http://localhost:4300/api/v1/users/login
Content-Type: application/json

{
    "email_user": "profesor@example.com",
    "password_user": "securePassword123"
}

### Cerrar sesión
POST http://localhost:4300/api/v1/users/logout/2

### Eliminar usuario
DELETE http://localhost:4300/api/v1/users/delete/1

### Obtener información del usuario
GET http://localhost:4300/api/v1/users/2

### Actualizar información del usuario
PATCH http://localhost:4300/api/v1/users/update/2
Content-Type: multipart/form-data; boundary=--CustomBoundary


----CustomBoundary
Content-Disposition: form-data; name="name_user"

Jose S. Santana
----CustomBoundary
Content-Disposition: form-data; name="avatar_imagen"; filename="profile.jpg"
Content-Type: image/jpeg

./uploads/profile.jpg
----CustomBoundary
Content-Disposition: form-data; name="bio"

Aspiring developer with a passion for learning and creating innovative solutions.
----CustomBoundary
Content-Disposition: form-data; name="username"

josesantana_dev
----CustomBoundary----



